### PR TITLE
core: Clamp BLDY to 0..16 in compose_pixel

### PR DESCRIPTION
**Pull request by xTibor**
As per the GBATEK docs. Fixes the fadeout animations in Ice Age.

### CODE REVIEW

**Comment by xTibor** [comment]
Just noticed BLDALPHA will also need the same treatment. Would be nice to find some code that hits this to test with.

<pre>
4000052h - BLDALPHA - Alpha Blending Coefficients (R/W) (not W)
0-4   EVA Coefficient (1st Target) (0..16 = 0/16..16/16, <b>17..31=16/16</b>)  
8-12  EVB Coefficient (2nd Target) (0..16 = 0/16..16/16, <b>17..31=16/16</b>)
<pre>

**Comment by michelhe** [comment]
Wouldn't it better performance-wise to do the actual clamping only when the CPU writes to BLDY and BLDALPHA?
(At least BLDY is supposed to be write-only so It doesn't matter)

BTW, Thanks for helping out and noticing these issues!

**Comment by xTibor** [comment]
Yep, it could be truncated in the write op, but that means false information will show up in the debugger (`gpuinfo`) about what was written to the register. I just wanted to avoid that.

**Comment by michelhe** [comment]
I think it's alright since the debugger is intended to depict the actual state of the hardware.

**Comment by michelhe** [comment]
@xTibor I'm merging this, I'll test later if the clamping can be done with BLDALPHA on the write-operation (since its a readable register) and add it

**Comment by xTibor** [comment]
Okay. I left the alpha out of the PR because I didn't find any games that hit this bug to experiment with.

**Pull request merged**
