### PR TITLE
Work towards having passing Travis CI

### PR DESCRIPTION
**Pull request by xTibor**
Thumb tests are now passing, the ARM tests are still failing.

### CODE REVIEW

**Comment by xTibor** [comment]
Turns the Travis failure from this:

```
error: couldn't read rustboyadvance-core/src/../../../external/gba-suite/arm/arm.gba: No such file or directory (os error 2)
   --> rustboyadvance-core/src/gba.rs:302:37
    |
302 |         let mut gba = make_mock_gba(include_bytes!("../../../external/gba-suite/arm/arm.gba"));
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
error: couldn't read rustboyadvance-core/src/../../../external/gba-suite/thumb/thumb.gba: No such file or directory (os error 2)
   --> rustboyadvance-core/src/gba.rs:315:37
    |
315 |           let mut gba = make_mock_gba(include_bytes!(
    |  _____________________________________^
316 | |             "../../../external/gba-suite/thumb/thumb.gba"
317 | |         ));
    | |_________^m
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

... to this:

```
running 4 tests
test cartridge::backup::eeprom::tests::test_spi_read_write ... ok
test gba::tests::test_arm7tdmi_thumb_eggvance ... ok
test gpu::layer::tests::test_layer_sort_order ... ok
test gba::tests::test_arm7tdmi_arm_eggvance ... FAILED
failures:
---- gba::tests::test_arm7tdmi_arm_eggvance stdout ----
thread 'gba::tests::test_arm7tdmi_arm_eggvance' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `207`', rustboyadvance-core/src/gba.rs:310:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    gba::tests::test_arm7tdmi_arm_eggvance
test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by michelhe** [comment]
Oh nice I didn't know endrift updated the mgba test suite!

**Comment by michelhe** [comment]
@xTibor Could you give me write-access to this branch so I can add changes?

**Comment by xTibor** [comment]
"Allow edits by maintainers" box is checked on the PR, you should be able to edit it.

**Comment by michelhe** [comment]
Nvm I'll merge this and commit to master 🤓

**Pull request merged**
