### PR TITLE
core: Add error handling to cartridge header parsing

### PR DESCRIPTION
**Pull request by xTibor**

### CODE REVIEW

**Comment by michelhe** [comment]
This breaks the JNI binding crate
https://github.com/michelhe/rustboyadvance-ng/blob/master/bindings/rustboyadvance-jni/src/rom_helper.rs#L9

Looks like its about time I make a decent CI 😨

**Comment by xTibor** [comment]
Sorry, I didn't notice that failure. It just needs unwrapping there because header parsing now returns a `Result`.

**Comment by michelhe** [comment]
Yes, but unwrapping will crash the java VM. Since you are providing nice error messages, it would be better to throw a java exception, like here for example:
https://github.com/michelhe/rustboyadvance-ng/blob/master/bindings/rustboyadvance-jni/src/lib.rs#L187

But we'll have to update the Java wrapper (https://github.com/michelhe/rustboyadvance-ng/blob/master/platform/android/app/src/main/java/com/mrmichel/rustboyadvance/RomHelper.java#L9)
 with a `throws` declaration.

**Comment by michelhe** [comment]
As for the wasm wrapper, unwrapping is fine because the panic will show up in the browser developer console

**Comment by michelhe** [comment]
Since we were still unwrapping before this change, there is no reason not to merge already ^^
For later I'll probably do a panic hook similar to the one in `rustboyadvance-wasm`  instead of explicitly throwing java exceptions every time.

**Pull request merged**
